### ISSUE TITLE
No Output Produced

### ISSUE THREAD

**Issue by Jafar717** [IgniparousTempest/py-minutiae-viewer#2]
Hi there,

I discovered that the following command fails to produce the output "out":

    command = ' '.join([str(mindtct_path), '-m1', str(image_path), str(output_path)])
    os.system(command)

Is "mindtct.exe" ever supposed to output the minutiae like that?

Regards,
Jafar

**Comment by IgniparousTempest** [comment]
It should? The [line 34](https://github.com/IgniparousTempest/py-minutiae-viewer/blob/0eb5f1f5286895e5a10dc13c84815692ec0d46f2/pyminutiaeviewer/mindtct/__init__.py#L34) sets up the mindtct command and [line 41](https://github.com/IgniparousTempest/py-minutiae-viewer/blob/0eb5f1f5286895e5a10dc13c84815692ec0d46f2/pyminutiaeviewer/mindtct/__init__.py#L41) deletes the temporary folder that the output files are in. If you want to preserve the output files, then comment out line 41.

Does that answer your question?

Or are you saying that mindtct fails to work? If it fails to work, could you tell me a bit more about your system, e.g. operating system and version.

**Comment by druvakumar12** [comment]
Hi, I am getting this error while i run

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Public\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "S:\Office\finger\work\20_08_20\py-minutiae-viewer-master\pyminutiaeviewer\gui_mindtct.py", line 80, in extract_minutiae
    minutiae = mindtct(im)
  File "S:\Office\finger\work\20_08_20\py-minutiae-viewer-master\pyminutiaeviewer\mindtct\__init__.py", line 38, in mindtct
    minutiae = reader.read(str(output_path) + '.min')
  File "S:\Office\finger\work\20_08_20\py-minutiae-viewer-master\pyminutiaeviewer\minutiae_reader.py", line 37, in read
    with open(absolute_file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\E1-572G\\AppData\\Local\\Temp\\pyminview_puvpgx82\\out.min'

**Comment by ud38** [comment]
Sir, I am working on google colab, Can you provide Jupiter notebook version of the python code, please.
